/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Prottery } from "./Prottery";
export * as factories from "./factories";
export { Prottery__factory } from "./factories/Prottery__factory";
